webtalk_init -webtalk_dir /home/Alvinna/Desktop/lab6/lab6.sim/sim_1/behav/xsim/xsim.dir/lab6_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 25 22:41:25 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7cf0e9f9-6033-4f89-a6ed-282ad67afeaa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ac3094ea0c434360b7cb968725c631e4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Gentoo" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Gentoo Base System release 2.6" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1056.405 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "214598065 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "19.40_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123416_KB" -context "xsim\\usage"
webtalk_transmit -clientid 257943937 -regid "" -xml /home/Alvinna/Desktop/lab6/lab6.sim/sim_1/behav/xsim/xsim.dir/lab6_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/Alvinna/Desktop/lab6/lab6.sim/sim_1/behav/xsim/xsim.dir/lab6_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/Alvinna/Desktop/lab6/lab6.sim/sim_1/behav/xsim/xsim.dir/lab6_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
